# Generated by Django 5.2.2 on 2025-11-05 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_postanalytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postingjob',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who started this posting job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posting_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
