"""
Session Format Converter
Converts between browser-exported cookie format and Playwright storage_state format
"""

import json


def convert_browser_to_playwright(browser_cookies):
    """
    Convert browser-exported cookie array to Playwright storage_state format

    Args:
        browser_cookies: List of cookies from browser export

    Returns:
        dict: Playwright storage_state format
    """
    playwright_cookies = []

    for cookie in browser_cookies:
        playwright_cookie = {
            "name": cookie.get("name"),
            "value": cookie.get("value"),
            "domain": cookie.get("domain"),
            "path": cookie.get("path"),
            "secure": cookie.get("secure", True),
            "httpOnly": cookie.get("httpOnly", False),
        }

        # Handle sameSite conversion
        same_site = cookie.get("sameSite")
        if same_site == "no_restriction":
            playwright_cookie["sameSite"] = "None"
        elif same_site == "lax":
            playwright_cookie["sameSite"] = "Lax"
        elif same_site == "strict":
            playwright_cookie["sameSite"] = "Strict"
        elif same_site is None or same_site == "unspecified":
            playwright_cookie["sameSite"] = "Lax"  # Default
        else:
            playwright_cookie["sameSite"] = same_site

        # Handle expires/expirationDate
        if "expirationDate" in cookie:
            playwright_cookie["expires"] = cookie["expirationDate"]
        elif "expires" in cookie:
            playwright_cookie["expires"] = cookie["expires"]
        else:
            # Session cookie (no expiration)
            playwright_cookie["expires"] = -1

        playwright_cookies.append(playwright_cookie)

    # Create Playwright storage_state format
    storage_state = {
        "cookies": playwright_cookies,
        "origins": []  # localStorage will be regenerated by Facebook
    }

    return storage_state


def is_browser_format(data):
    """
    Detect if session data is in browser export format

    Args:
        data: Session data (dict or list)

    Returns:
        bool: True if browser format, False if Playwright format
    """
    # Browser format is a list of cookies
    if isinstance(data, list):
        if len(data) > 0 and isinstance(data[0], dict):
            # Check for browser-specific properties
            return "expirationDate" in data[0] or "hostOnly" in data[0]

    # Playwright format is an object with 'cookies' key
    if isinstance(data, dict):
        return False

    return False


def auto_convert_session(session_data):
    """
    Automatically detect and convert session format if needed

    Args:
        session_data: Session data in either format

    Returns:
        dict: Playwright storage_state format
    """
    if is_browser_format(session_data):
        print("🔄 Detected browser cookie format, converting to Playwright format...")
        return convert_browser_to_playwright(session_data)
    else:
        print("✅ Already in Playwright format, no conversion needed")
        return session_data


def load_and_convert_session(session_path):
    """
    Load session file and convert to Playwright format if needed

    Args:
        session_path: Path to session JSON file

    Returns:
        dict: Playwright storage_state format
    """
    with open(session_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    return auto_convert_session(data)


def save_playwright_session(session_data, output_path):
    """
    Save session in Playwright format

    Args:
        session_data: Session data in Playwright format
        output_path: Where to save the file
    """
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(session_data, f, indent=2)

    print(f"✅ Session saved: {output_path}")


# Example usage
if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print(
            "Usage: python session_converter.py <session_file.json> [output_file.json]")
        print("\nExample:")
        print("  python session_converter.py sessions/posttomarketplace_gmail_com3.json")
        print("  python session_converter.py sessions/browser_export.json sessions/converted.json")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(
        sys.argv) > 2 else input_file.replace('.json', '_converted.json')

    print(f"📂 Loading: {input_file}")
    converted = load_and_convert_session(input_file)

    print(f"💾 Saving to: {output_file}")
    save_playwright_session(converted, output_file)

    print("\n✅ Conversion complete!")
    print(f"📊 Cookies count: {len(converted['cookies'])}")
